name: Bug report for .NET nanoFramework documentation
description: Create a bug report related with our documentation or website.
labels: 
  - "documentation"
  - "Status: Waiting triage"
body:
  - type: markdown
    attributes:
      value: |
        # :warning: **Please read before raising the issue** :warning:

        If you have a **question**, need clarification on something, need help on a particular situation or want to start a discussion, **DO NOT** open an issue here. _It will be automatically closed!_ 
        
        Ask the question on one of our [Discord channels](https://discordapp.com/invite/gCyBu8T), making sure to select the channel that's most appropriate to the context so subject matter experts are most likely to answer promptly. 
        If you're not keen to Discord, you can also use [GitHub Discussions](https://github.com/nanoframework/Home/discussions) in this same repo.
        Or, alternatively, on [Stack Overflow](https://stackoverflow.com/questions/tagged/nanoframework) using the `nanoframework` tag. 

        If you realy want to raise an issue, please make sure to follow the template and provide the required information. Failing to do so will most likely end up on the issue being close. Don't take offense at this. It is simply a time management decision. Whenever an issue is raised without following the template and the required information is not provided, very often too much time has to be spent going back and forth to obtain the details that are outlined below.

  - type: dropdown
    id: location
    attributes:
      label: Location
      description: Where is the error you're reporting.
      multiple: false
      options:
        - Docs website
        - GitHub README
        - Official website
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Cold be helpful if you send along a few screenshots to help visualize the issue!
      placeholder: drag and drop here, if applicable
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        ### Make an effort to fix the bug
        
        Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug (except if it is on a location that's not open source, like the website).

        <!-- bug-report-docs-tag DO NOT REMOVE -->
